"""
Per-agent psychological trait vectors.

Traits are numeric in [0, 1] (except sentiment_bias in [-1, 1]) so they can be
generated by the config LLM, swept in experiments, and fitted against real
data. They are rendered into the agent's system prompt as operational
instructions -- not vague adjectives -- because prompt-level bias induction is
the mechanism with the strongest published validation (it is sufficient to
reproduce ideological clustering / opinion fragmentation in LLM populations).

Trait sources, in priority order:
1. `agent_configs[i].psych` block generated by SimulationConfigGenerator
2. legacy fields on the agent config (`sentiment_bias`, `stance`)
3. deterministic per-agent fallback sampling (seeded by agent_id so runs
   are reproducible)
"""

import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Bias library: operational instructions, not labels.
#
# Each entry maps a bias id to a second-person instruction that an LLM can
# actually act on while role-playing. Keep instructions behavioral ("you do X
# when Y") rather than definitional ("you have X bias").
# ---------------------------------------------------------------------------
BIAS_LIBRARY: Dict[str, str] = {
    "confirmation_bias": (
        "You interpret ambiguous information as confirming what you already "
        "believe, and you scrutinize opposing evidence far more harshly than "
        "supporting evidence."
    ),
    "negativity_bias": (
        "Negative or alarming information grabs your attention much more than "
        "positive news, and you weigh it more heavily when forming judgments."
    ),
    "bandwagon_effect": (
        "When you see that many people share an opinion, you feel strong pull "
        "to agree with it; highly-liked posts seem more credible to you."
    ),
    "authority_bias": (
        "You accept claims from officials, experts, and verified or "
        "high-follower accounts with little scrutiny, and doubt claims from "
        "unknown accounts."
    ),
    "availability_heuristic": (
        "You judge how common or likely something is by how easily examples "
        "come to mind -- vivid recent posts dominate your sense of reality."
    ),
    "illusory_truth": (
        "The more often you see a claim repeated, the more true it feels to "
        "you, regardless of the source."
    ),
    "in_group_favoritism": (
        "You trust and amplify people who share your identity or stance, and "
        "are suspicious and dismissive toward out-group voices."
    ),
    "emotional_reasoning": (
        "You treat your emotional reaction as evidence: if something makes "
        "you angry or afraid, you conclude it must be true and important."
    ),
    "anchoring": (
        "The first number or claim you encounter on a topic strongly anchors "
        "your later estimates and judgments, even when it is arbitrary."
    ),
    "false_consensus": (
        "You assume most reasonable people privately agree with you, so "
        "disagreement reads as bad faith or manipulation."
    ),
    "reactance": (
        "When you feel authorities or platforms are telling you what to "
        "think, you push back and become more attached to the forbidden view."
    ),
    "sunk_cost": (
        "Once you have publicly defended a position, you double down rather "
        "than concede, because backing off feels like a loss."
    ),
}

# Entity-type priors for fallback sampling: (biases pool, trait ranges).
# Institutions are calmer and less impulsive than individuals.
_INDIVIDUAL_TYPES = {
    "student", "alumni", "professor", "person", "publicfigure",
    "expert", "faculty", "official", "journalist", "activist",
}


@dataclass
class PsychProfile:
    """Numeric psychological profile of one agent."""

    agent_id: int
    biases: List[str] = field(default_factory=list)
    # How readily the agent believes unverified claims (widens opinion
    # confidence bound, raises misinformation susceptibility).
    credulity: float = 0.5
    # Susceptibility to social proof (scales opinion convergence rate).
    conformity: float = 0.5
    # Extra weight on negative/alarming content in perception re-ranking.
    negativity_bias: float = 0.5
    # Probability scale of impulsive (System-1 / choice-noise) behavior.
    impulsivity: float = 0.5
    # High need-for-cognition agents deliberate more (System-2).
    need_for_cognition: float = 0.5
    # Baseline mood tint, -1 (negative) .. 1 (positive). Was a dead config
    # field before this package existed; now live.
    sentiment_bias: float = 0.0
    # supportive / opposing / neutral / observer -- seeds initial opinion.
    stance: str = "neutral"
    # Per-topic initial opinions in [-1, 1]; missing topics fall back to
    # the stance-derived default.
    opinions: Dict[str, float] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def from_agent_config(cls, cfg: Dict[str, Any]) -> "PsychProfile":
        """Build a profile from one agent_configs entry.

        Uses the `psych` block when present, otherwise derives sensible,
        reproducible values from legacy fields + seeded randomness.
        """
        agent_id = int(cfg.get("agent_id", 0))
        psych = cfg.get("psych") or {}
        stance = str(cfg.get("stance", psych.get("stance", "neutral")))
        sentiment_bias = _clip(
            float(cfg.get("sentiment_bias", psych.get("sentiment_bias", 0.0))),
            -1.0, 1.0,
        )

        if psych:
            profile = cls(
                agent_id=agent_id,
                biases=[b for b in psych.get("biases", []) if b in BIAS_LIBRARY],
                credulity=_clip01(psych.get("credulity", 0.5)),
                conformity=_clip01(psych.get("conformity", 0.5)),
                negativity_bias=_clip01(psych.get("negativity_bias", 0.5)),
                impulsivity=_clip01(psych.get("impulsivity", 0.5)),
                need_for_cognition=_clip01(psych.get("need_for_cognition", 0.5)),
                sentiment_bias=sentiment_bias,
                stance=stance,
                opinions={
                    str(k): _clip(float(v), -1.0, 1.0)
                    for k, v in (psych.get("opinions") or {}).items()
                },
            )
            if not profile.biases:
                profile.biases = _sample_biases(agent_id, cfg)
            return profile

        # Legacy config without a psych block: deterministic fallback.
        rng = random.Random(10_000 + agent_id)
        entity_type = str(cfg.get("entity_type", "")).lower()
        is_individual = entity_type in _INDIVIDUAL_TYPES
        spread = 0.35 if is_individual else 0.15
        center = 0.5 if is_individual else 0.35
        return cls(
            agent_id=agent_id,
            biases=_sample_biases(agent_id, cfg),
            credulity=_clip01(rng.gauss(center, spread)),
            conformity=_clip01(rng.gauss(center, spread)),
            negativity_bias=_clip01(rng.gauss(center, spread)),
            impulsivity=_clip01(rng.gauss(center if is_individual else 0.2, spread)),
            need_for_cognition=_clip01(rng.gauss(0.5, spread)),
            sentiment_bias=sentiment_bias,
            stance=stance,
        )

    # ------------------------------------------------------------------
    # Derived values
    # ------------------------------------------------------------------

    def initial_opinion(self, topic: str) -> float:
        """Initial opinion for a topic, from explicit map or stance default."""
        if topic in self.opinions:
            return self.opinions[topic]
        stance_defaults = {
            "supportive": 0.7,
            "opposing": -0.7,
            "neutral": 0.0,
            "observer": 0.0,
        }
        base = stance_defaults.get(self.stance, 0.0)
        # Small deterministic jitter so a stance cohort is not a single point
        # (uniform cohorts collapse opinion dynamics into three deltas).
        rng = random.Random(20_000 + self.agent_id + hash(topic) % 1000)
        return _clip(base + rng.uniform(-0.15, 0.15), -1.0, 1.0)

    # ------------------------------------------------------------------
    # Prompt rendering
    # ------------------------------------------------------------------

    def render_prompt_section(self, intensity: float = 1.0) -> str:
        """Render the trait vector as an operational system-prompt section.

        `intensity` in [0, 1+] globally scales how strongly traits are
        phrased; at 0 the section is empty (feature effectively off).
        """
        if intensity <= 0:
            return ""

        lines = ["# PSYCHOLOGICAL PROFILE",
                 "These dispositions shape how you read and react to content. "
                 "They are part of who you are -- act on them, do not mention them."]

        for bias_id in self.biases:
            instruction = BIAS_LIBRARY.get(bias_id)
            if instruction:
                lines.append(f"- {instruction}")

        lines.append(
            f"- {_scale_phrase(self.credulity * intensity, 'You fact-check claims before believing them', 'You take claims at face value and rarely verify anything')}."
        )
        lines.append(
            f"- {_scale_phrase(self.conformity * intensity, 'You hold your view even when everyone disagrees', 'You quickly align your view with the crowd around you')}."
        )
        lines.append(
            f"- {_scale_phrase(self.impulsivity * intensity, 'You think carefully before reacting', 'You react immediately on gut feeling, often before reading fully')}."
        )
        if self.sentiment_bias >= 0.3:
            lines.append("- Your default mood online is upbeat; you give people the benefit of the doubt.")
        elif self.sentiment_bias <= -0.3:
            lines.append("- Your default mood online is irritable and pessimistic; you expect the worst from people and institutions.")

        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "agent_id": self.agent_id,
            "biases": list(self.biases),
            "credulity": self.credulity,
            "conformity": self.conformity,
            "negativity_bias": self.negativity_bias,
            "impulsivity": self.impulsivity,
            "need_for_cognition": self.need_for_cognition,
            "sentiment_bias": self.sentiment_bias,
            "stance": self.stance,
            "opinions": dict(self.opinions),
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sample_biases(agent_id: int, cfg: Dict[str, Any]) -> List[str]:
    """Deterministically sample 2-4 biases for an agent lacking explicit ones."""
    rng = random.Random(30_000 + agent_id)
    pool = list(BIAS_LIBRARY.keys())
    entity_type = str(cfg.get("entity_type", "")).lower()
    if entity_type not in _INDIVIDUAL_TYPES:
        # Institutional accounts: fewer hot-cognition biases.
        for hot in ("emotional_reasoning", "reactance", "impulsivity"):
            if hot in pool:
                pool.remove(hot)
        return rng.sample(pool, k=2)
    return rng.sample(pool, k=rng.randint(2, 4))


def _scale_phrase(value: float, low_phrase: str, high_phrase: str) -> str:
    """Map a [0,1] trait to graded second-person phrasing."""
    if value < 0.25:
        return low_phrase
    if value < 0.5:
        return f"Somewhat: {high_phrase.lower()}, though only mildly"
    if value < 0.75:
        return high_phrase
    return f"{high_phrase} -- this is one of your defining traits"


def _clip(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, float(value)))


def _clip01(value: float) -> float:
    return _clip(value, 0.0, 1.0)
